name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test:ci

      - name: Archive report
        uses: actions/upload-artifact@v1
        with:
          name: cucumber-report
          path: report.html
